import type { Investor } from '../types'

export const INVESTORS: Investor[] = [
  {
    id: 'buffett',
    name: 'Warren Buffett',
    shortName: 'Buffett',
    era: '1965–present',
    style: 'Quality at Fair Price',
    tagline: 'Wonderful companies at fair prices',
    avatar: 'WB',
    color: '#3b82f6',
    ctx: `Apply Warren Buffett's documented investment framework from his Berkshire Hathaway letters and public writings. The framework prioritises durable competitive advantages (moats), consistent earnings power, high returns on equity without excessive debt, capable owner-oriented management, and buying wonderful businesses at fair prices. Emphasise long-term business quality over short-term metrics. Apply the circle of competence principle — if the business is too complex to understand within a reasonable timeframe, note this explicitly. This is an educational application of Buffett's publicly documented philosophy, not affiliated with or endorsed by Buffett or Berkshire Hathaway.`,
    rules: [
      { id: 'moat', label: 'Durable Moat', description: 'Wide competitive advantage that protects earnings for 10+ years' },
      { id: 'roe', label: 'ROE > 15%', description: 'Consistent return on equity above 15% for 5+ years without excessive leverage' },
      { id: 'debt', label: 'Low Debt', description: 'Debt-to-equity < 0.5; can service debt from earnings easily' },
      { id: 'earnings', label: 'Consistent Earnings', description: 'Predictable, growing earnings over a business cycle' },
      { id: 'mgmt', label: 'Owner-Oriented Management', description: 'Management that thinks like owners; avoids dilution and foolish acquisitions' },
      { id: 'price', label: 'Fair Price', description: 'Intrinsic value exceeds market price by a reasonable margin' },
    ],
    equations: [
      { label: 'Owner Earnings', formula: 'Net Income + D&A − CapEx − Working Capital Change' },
      { label: 'IV (simple)', formula: 'Owner Earnings / (Discount Rate − Growth Rate)' },
    ],
  },
  {
    id: 'graham',
    name: 'Benjamin Graham',
    shortName: 'Graham',
    era: '1930–1972',
    style: 'Deep Value / Net-Net',
    tagline: 'Margin of safety above all else',
    avatar: 'BG',
    color: '#8b5cf6',
    ctx: `Apply Benjamin Graham's documented value investing framework from Security Analysis and The Intelligent Investor. The framework applies strict quantitative criteria and prioritises margin of safety — only considering a stock attractive when price is significantly below intrinsic value. Primary valuation tools are net current asset value (NCAV), earnings yield, and the Graham Number. The framework is sceptical of growth projections; it focuses on what is provably cheap by the numbers and prefers asset-backed valuations. This is an educational application of Graham's publicly documented philosophy, not affiliated with or endorsed by the Graham estate.`,
    rules: [
      { id: 'pe', label: 'P/E < 15', description: 'Current P/E below 15 to ensure you are not overpaying for earnings' },
      { id: 'pb', label: 'P/B < 1.5', description: 'Price-to-book below 1.5; ideally below book value' },
      { id: 'graham_num', label: 'Graham Number', description: 'Price < Graham Number (√(22.5 × EPS × BVPS))' },
      { id: 'current', label: 'Current Ratio > 2', description: 'Current assets at least 2× current liabilities for financial safety' },
      { id: 'debt_nc', label: 'LT Debt < Net Current Assets', description: 'Long-term debt does not exceed net current assets' },
      { id: 'earnings_stability', label: '10yr Earnings Stability', description: 'Positive earnings in each of the past 10 years' },
    ],
    equations: [
      { label: 'Graham Number', formula: '√(22.5 × EPS × Book Value Per Share)' },
      { label: 'NCAV', formula: 'Current Assets − Total Liabilities' },
    ],
  },
  {
    id: 'lynch',
    name: 'Peter Lynch',
    shortName: 'Lynch',
    era: '1977–1990',
    style: 'GARP / Growth at Reasonable Price',
    tagline: 'Invest in what you know',
    avatar: 'PL',
    color: '#10b981',
    ctx: `Apply Peter Lynch's GARP (Growth at Reasonable Price) framework documented in One Up on Wall Street and Beating the Street. The framework uses the PEG ratio as its primary valuation metric — PEG below 1 is considered attractive. It categorises stocks by type: slow growers, stalwarts, fast growers, cyclicals, turnarounds, and asset plays. The framework favours companies with simple business models and looks for underfollowed stocks with strong fundamentals and realistic growth prospects. Over-diversification ("diworsification") is viewed negatively. This is an educational application of Lynch's publicly documented philosophy, not affiliated with or endorsed by Lynch or Fidelity.`,
    rules: [
      { id: 'peg', label: 'PEG < 1', description: 'PEG ratio below 1 indicates growth is not fully priced in' },
      { id: 'simple', label: 'Simple Business', description: 'Business model simple enough to explain in two minutes' },
      { id: 'growth', label: 'Earnings Growth', description: 'Consistent earnings growth matching or exceeding the growth rate implied by P/E' },
      { id: 'inventory', label: 'Inventory Check', description: 'Inventory not growing faster than sales (for manufacturers)' },
      { id: 'insider', label: 'Insider Buying', description: 'Management buying shares on the open market is a positive signal' },
      { id: 'category', label: 'Category Fit', description: 'Clearly fits a Lynch stock category with a defined catalyst' },
    ],
    equations: [
      { label: 'PEG Ratio', formula: 'P/E ÷ Annual EPS Growth Rate' },
      { label: 'Lynch Fair Value', formula: 'EPS × Growth Rate (%)' },
    ],
  },
  {
    id: 'munger',
    name: 'Charlie Munger',
    shortName: 'Munger',
    era: '1962–2023',
    style: 'Mental Models / Latticework',
    tagline: 'Invert, always invert',
    avatar: 'CM',
    color: '#f59e0b',
    ctx: `Apply Charlie Munger's multidisciplinary investment framework documented through his speeches, Poor Charlie's Almanack, and Berkshire Hathaway letters. The framework employs a latticework of mental models across disciplines. A key tool is inversion — asking what would cause an investment to fail, then checking for those conditions. The framework looks for businesses with genuine pricing power and network effects, applies circle of competence rigorously, and focuses on business model quality over headline numbers. Management incentives misaligned with shareholders are viewed as disqualifying. This is an educational application of Munger's publicly documented philosophy, not affiliated with or endorsed by Munger's estate or Berkshire Hathaway.`,
    rules: [
      { id: 'pricing_power', label: 'Pricing Power', description: 'Company can raise prices without losing significant volume' },
      { id: 'network', label: 'Network Effect', description: 'Product or service becomes more valuable as more people use it' },
      { id: 'inversion', label: 'Inversion Test', description: 'Business model survives inversion — hard to destroy even with deliberate effort' },
      { id: 'incentives', label: 'Aligned Incentives', description: 'Management compensation tied to long-term shareholder value creation' },
      { id: 'moat_quality', label: 'Moat Quality', description: 'Competitive advantage is structural, not just operational efficiency' },
      { id: 'simplicity', label: 'Business Simplicity', description: 'Business is understandable; no black-box complexity' },
    ],
    equations: [
      { label: 'Owner Earnings Yield', formula: 'Owner Earnings ÷ Market Cap' },
      { label: 'Normalised ROE', formula: 'Avg Net Income (5yr) ÷ Avg Equity (5yr)' },
    ],
  },
  {
    id: 'greenblatt',
    name: 'Joel Greenblatt',
    shortName: 'Greenblatt',
    era: '1985–present',
    style: 'Magic Formula / Earnings Yield',
    tagline: 'Good companies at bargain prices — systematically',
    avatar: 'JG',
    color: '#ec4899',
    ctx: `Apply Joel Greenblatt's Magic Formula framework documented in The Little Book That Beats the Market. The framework ranks companies by two metrics: earnings yield (EBIT/Enterprise Value) and return on capital (EBIT/Net Fixed Assets + Working Capital), favouring companies that rank highly on both simultaneously. It seeks above-average businesses at below-average prices. The formula explicitly does not apply to highly leveraged companies, utilities, or financials. Special situations — spinoffs, restructurings, mergers — can offer excess returns when the market misprices their complexity. This is an educational application of Greenblatt's publicly documented methodology, not affiliated with or endorsed by Greenblatt or Gotham Asset Management.`,
    rules: [
      { id: 'ey', label: 'Earnings Yield > 10%', description: 'EBIT/EV above 10% — getting good earnings for your dollar' },
      { id: 'roc', label: 'Return on Capital > 25%', description: 'EBIT/(Net Fixed Assets + Working Capital) above 25%' },
      { id: 'combo_rank', label: 'Combined Rank', description: 'High combined rank on both EY and ROC in its industry' },
      { id: 'no_fin', label: 'Not a Financial/Utility', description: 'Magic Formula does not apply to banks, insurers, or utilities' },
      { id: 'special_sit', label: 'Special Situation Bonus', description: 'Spinoff, restructuring, or complexity creating temporary mispricing' },
      { id: 'leverage', label: 'Manageable Leverage', description: 'Not heavily leveraged — debt amplifies downside in bad years' },
    ],
    equations: [
      { label: 'Earnings Yield', formula: 'EBIT ÷ Enterprise Value' },
      { label: 'Return on Capital', formula: 'EBIT ÷ (Net Fixed Assets + Net Working Capital)' },
    ],
  },
  {
    id: 'dalio',
    name: 'Ray Dalio',
    shortName: 'Dalio',
    era: '1975–present',
    style: 'Macro / Risk Parity',
    tagline: 'Radical transparency and systematic thinking',
    avatar: 'RD',
    color: '#06b6d4',
    ctx: `Apply Ray Dalio's macro-economic investment framework documented in Principles, Principles for Navigating Big Debt Crises, and Bridgewater research. The framework evaluates stocks in the context of the long-term debt cycle, short-term economic cycle, and productivity trends. It uses the "All Weather" approach — assessing how an asset performs across rising/falling growth and rising/falling inflation scenarios. Balance sheet resilience for a downturn scenario is a central consideration. The framework is especially attentive to debt levels, currency risk, and central bank policy impact. This is an educational application of Dalio's publicly documented philosophy, not affiliated with or endorsed by Dalio or Bridgewater Associates.`,
    rules: [
      { id: 'cycle', label: 'Cycle Position', description: 'Company positioned well within current debt and economic cycle' },
      { id: 'balance_sheet', label: 'Balance Sheet Resilience', description: 'Can survive a severe recession without existential threat' },
      { id: 'currency', label: 'Currency Risk', description: 'International revenue diversified or hedged appropriately' },
      { id: 'real_return', label: 'Real Return Positive', description: 'Expected return exceeds inflation rate over the investment horizon' },
      { id: 'correlation', label: 'Low Correlation', description: 'Business is not highly correlated with broader market in downturns' },
      { id: 'debt_service', label: 'Debt Service Capacity', description: 'Interest coverage ratio above 5× on normalised earnings' },
    ],
    equations: [
      { label: 'Debt/EBITDA', formula: 'Total Debt ÷ EBITDA' },
      { label: 'Interest Coverage', formula: 'EBIT ÷ Interest Expense' },
    ],
  },
  {
    id: 'marks',
    name: 'Howard Marks',
    shortName: 'Marks',
    era: '1978–present',
    style: 'Distressed / Risk-Aware',
    tagline: 'Superior performance comes from superior risk control',
    avatar: 'HM',
    color: '#a78bfa',
    ctx: `Apply Howard Marks' risk-aware investment framework documented in The Most Important Thing and his Oaktree Capital memos. The framework centres on second-level thinking — not just what is going to happen, but what the consensus expects to happen, and whether a differentiated edge exists over that consensus. Risk is defined not as volatility but as the probability and magnitude of permanent loss. The framework seeks investments where risk/reward is skewed positively — bad outcomes limited, good outcomes meaningful. It is cautious at market peaks and more aggressive at troughs. This is an educational application of Marks' publicly documented philosophy, not affiliated with or endorsed by Marks or Oaktree Capital.`,
    rules: [
      { id: 'second_level', label: 'Second-Level Insight', description: 'You have a differentiated view from market consensus based on evidence' },
      { id: 'risk_reward', label: 'Asymmetric Risk/Reward', description: 'Downside is limited; upside is significant relative to the risk taken' },
      { id: 'cycle_awareness', label: 'Cycle Awareness', description: 'Understanding where we are in market and credit cycles' },
      { id: 'perm_loss', label: 'Low Permanent Loss Risk', description: 'Probability of permanent capital impairment is low' },
      { id: 'consensus', label: 'Consensus Deficiency', description: 'Market consensus has a provable flaw you have identified' },
      { id: 'margin', label: 'Margin of Safety', description: 'Sufficient cushion between price and intrinsic value to absorb errors' },
    ],
    equations: [
      { label: 'Risk-Adj Return', formula: 'Expected Return ÷ Standard Deviation of Scenarios' },
      { label: 'Upside/Downside', formula: 'Expected Upside % ÷ Maximum Downside %' },
    ],
  },
  {
    id: 'klarman',
    name: 'Seth Klarman',
    shortName: 'Klarman',
    era: '1982–present',
    style: 'Absolute Value / Margin of Safety',
    tagline: 'Never risk permanent capital loss',
    avatar: 'SK',
    color: '#f97316',
    ctx: `Apply Seth Klarman's absolute-value investment framework documented in Margin of Safety. The framework practices absolute-return investing — focused exclusively on not losing money permanently, not on relative performance versus benchmarks. It applies very strict margin of safety requirements, only considering a security attractive at a substantial discount to intrinsic value. Valuation approaches include liquidation value, private market value, and sum-of-parts analysis. Significant cash holdings are appropriate when nothing meets the criteria. Speculative businesses with no near-term path to profitability are excluded. Value catalysts are an important consideration. This is an educational application of Klarman's publicly documented philosophy, not affiliated with or endorsed by Klarman or Baupost Group.`,
    rules: [
      { id: 'mos', label: 'Margin of Safety > 30%', description: 'Price at least 30% below conservatively estimated intrinsic value' },
      { id: 'liquidation', label: 'Liquidation Value', description: 'Consider what the business would be worth if liquidated today' },
      { id: 'catalyst', label: 'Value Catalyst', description: 'Identifiable catalyst that will cause market to recognise value' },
      { id: 'no_perm_loss', label: 'No Permanent Loss Path', description: 'No realistic scenario where capital is permanently impaired' },
      { id: 'tangible', label: 'Tangible Asset Backing', description: 'Significant tangible assets providing a floor to valuation' },
      { id: 'absolute', label: 'Absolute Return Focus', description: 'Return evaluated in absolute terms, not relative to an index' },
    ],
    equations: [
      { label: 'Margin of Safety', formula: '(Intrinsic Value − Price) ÷ Intrinsic Value' },
      { label: 'Private Market Value', formula: 'Comparable transaction multiples × Normalised EBITDA' },
    ],
  },
  {
    id: 'pabrai',
    name: 'Mohnish Pabrai',
    shortName: 'Pabrai',
    era: '1999–present',
    style: 'Clone / Focused Deep Value',
    tagline: 'Heads I win, tails I don\'t lose much',
    avatar: 'MP',
    color: '#84cc16',
    ctx: `Apply Mohnish Pabrai's Dhandho investment framework documented in The Dhandho Investor. The framework focuses on high-uncertainty, low-risk bets — situations where the market has conflated uncertainty with actual risk. A key element is cloning: following investments made by proven great investors when available at a discount. The framework applies Kelly Criterion thinking for position sizing, betting meaningfully on high-conviction ideas while limiting exposure to genuine downside. It is checklist-driven to avoid errors of omission and commission. This is an educational application of Pabrai's publicly documented philosophy, not affiliated with or endorsed by Pabrai or Pabrai Investment Funds.`,
    rules: [
      { id: 'dhandho', label: 'Dhandho Setup', description: 'High uncertainty, low actual risk — market is pricing in fear incorrectly' },
      { id: 'clone', label: 'Clone-able', description: 'Investment idea found or validated by a proven top investor' },
      { id: 'focused', label: 'High Conviction', description: 'You would bet more than 10% of portfolio — extreme clarity of thesis' },
      { id: 'heads_tails', label: 'Asymmetric Payoff', description: 'Heads I win big; tails I lose little — asymmetric payoff structure' },
      { id: 'moat_pabrai', label: 'Business Moat', description: 'Clear competitive advantage protecting returns on capital' },
      { id: 'checklist', label: 'Checklist Pass', description: 'Passes all items on investment checklist — no red flags' },
    ],
    equations: [
      { label: 'Payoff Ratio', formula: 'Expected Upside ÷ Expected Downside' },
      { label: 'Kelly Fraction', formula: '(bp − q) ÷ b  where b=odds, p=win prob, q=loss prob' },
    ],
  },
  {
    id: 'wood',
    name: 'Cathie Wood',
    shortName: 'Wood',
    era: '2014–present',
    style: 'Disruptive Innovation / ARK',
    tagline: 'Innovation is the key to growth',
    avatar: 'CW',
    color: '#f43f5e',
    ctx: `Apply Cathie Wood's disruptive innovation investment framework as documented through ARK Invest's published research and white papers. The framework focuses on technologies expected to dominate the next decade: AI, robotics, genomics, blockchain/fintech, and autonomous vehicles. It uses a 5-year price target methodology based on Wright's Law (cost curve decline with scale), total addressable market (TAM) expansion, and platform network effects. Companies in the "innovator's dilemma" sweet spot — disrupting incumbents in large markets — are strongly favoured. Traditional valuation metrics (P/E, FCF) are explicitly treated as less relevant; revenue growth trajectory and TAM capture potential are primary metrics. This is an educational application of ARK's publicly documented philosophy, not affiliated with or endorsed by Wood or ARK Invest.`,
    rules: [
      { id: 'disruption', label: 'Disruptive Technology', description: 'Company is deploying technology that will disrupt a large existing market' },
      { id: 'tam', label: 'Large TAM', description: 'Addressable market is at least $100B and expanding rapidly' },
      { id: 'wright', label: 'Wright\'s Law Curve', description: 'Cost curves are declining with production scale — sustainable advantage' },
      { id: 'network', label: 'Platform Network Effect', description: 'Platform becomes more valuable with each additional user/partner' },
      { id: 'growth', label: 'Revenue Growth > 25%', description: 'Annual revenue growth above 25% with a path to 40%+' },
      { id: 'convergence', label: 'Technology Convergence', description: 'Multiple disruptive technologies converging in the business model' },
    ],
    equations: [
      { label: '5yr Price Target', formula: 'Current Revenue × (1+g)^5 × Exit Multiple' },
      { label: 'TAM Capture', formula: 'Projected Market Share × Total Addressable Market' },
    ],
  },
  {
    id: 'fisher',
    name: 'Philip Fisher',
    shortName: 'Fisher',
    era: '1931–1999',
    style: 'Scuttlebutt / Quality Growth',
    tagline: 'Superior companies held forever',
    avatar: 'PF',
    color: '#14b8a6',
    ctx: `Apply Philip Fisher's quality-growth investment framework documented in Common Stocks and Uncommon Profits. The framework employs the Scuttlebutt method — gathering qualitative intelligence from competitors, customers, and suppliers — alongside a 15-point checklist. It seeks companies with superior products or services with significant long-term growth potential, deep management capability, and strong R&D commitment as a percentage of sales. Sales organisation effectiveness and profit margin trends are critical signals. The framework favours concentrated portfolios of truly outstanding companies held for very long periods. Management integrity and employee relations are weighted qualitative factors. Companies with cheap-looking statistics but weak underlying business characteristics are excluded. This is an educational application of Fisher's publicly documented philosophy, not affiliated with or endorsed by the Fisher estate.`,
    rules: [
      { id: 'market_potential', label: 'Significant Market Potential', description: 'Products/services with potential for substantial sales growth for many years' },
      { id: 'rd', label: 'Strong R&D', description: 'Company consistently reinvests in R&D as a percentage of sales' },
      { id: 'sales_org', label: 'Superior Sales Organisation', description: 'Best-in-class sales and distribution organisation in its sector' },
      { id: 'margins', label: 'Above-Average Margins', description: 'Profit margins above sector average with an upward trend' },
      { id: 'mgmt_integrity', label: 'Management Integrity', description: 'Management communicates honestly even when news is bad' },
      { id: 'employee', label: 'Employee Relations', description: 'Company known as an excellent employer in its industry' },
    ],
    equations: [
      { label: 'R&D Intensity', formula: 'R&D Expense ÷ Revenue' },
      { label: 'Sales Growth CAGR', formula: '(Revenue_n / Revenue_0)^(1/n) − 1' },
    ],
  },
  // ── New investors ─────────────────────────────────────────────────────────────

  {
    id: 'druckenmiller',
    name: 'Stanley Druckenmiller',
    shortName: 'Druckenmiller',
    era: '1981–present',
    style: 'Macro / Concentrated Momentum',
    tagline: 'Big bets when the risk/reward is overwhelmingly in your favour',
    avatar: 'SD',
    color: '#0ea5e9',
    ctx: `Apply Stanley Druckenmiller's macro-driven, concentrated investment framework as documented in his public interviews, presentations, and The New Market Wizards. The framework combines top-down macro analysis with bottom-up stock selection. The central principle is capital preservation first — never risk serious loss — followed by asymmetric position sizing: when the macro environment and company fundamentals align strongly, the framework calls for concentrated, conviction-sized bets. Druckenmiller's methodology emphasises liquidity, earnings momentum, earnings revisions, and the direction of central bank policy as key catalysts. He is famous for riding trends until they end rather than mean-reverting prematurely. Currency and interest rate tailwinds are integral to the setup. This is an educational application of Druckenmiller's publicly documented philosophy, not affiliated with or endorsed by Druckenmiller or Duquesne Family Office.`,
    rules: [
      { id: 'macro_align', label: 'Macro Tailwind', description: 'Central bank policy, credit cycle, and macro regime favour this sector/company' },
      { id: 'earnings_revision', label: 'Earnings Revisions Positive', description: 'Analyst earnings estimates are being revised upward — institutional money follows revisions' },
      { id: 'relative_strength', label: 'Relative Strength', description: 'Stock is outperforming its sector and the broader market over the past 3–6 months' },
      { id: 'asymmetric_payoff', label: 'Asymmetric Risk/Reward', description: 'Potential upside is at least 3× the potential downside in a clearly defined timeframe' },
      { id: 'liquidity', label: 'Sufficient Liquidity', description: 'Position can be entered and exited without significant market impact' },
      { id: 'catalyst', label: 'Near-Term Catalyst', description: 'Identifiable event within 6–18 months that will force market to reprice the stock' },
    ],
    equations: [
      { label: 'Risk/Reward Ratio', formula: 'Expected Upside % ÷ Maximum Drawdown Risk %' },
      { label: 'Position Size', formula: 'Kelly Fraction × (Edge ÷ Odds) — scaled by conviction level' },
    ],
  },

  {
    id: 'soros',
    name: 'George Soros',
    shortName: 'Soros',
    era: '1969–present',
    style: 'Macro / Reflexivity',
    tagline: 'Markets are always wrong; the question is the direction of the mispricing',
    avatar: 'GS',
    color: '#d97706',
    ctx: `Apply George Soros' reflexivity-based macro investment framework as documented in The Alchemy of Finance and his public interviews. The core concept is reflexivity: market participant perceptions can change the fundamentals they are supposed to merely reflect, creating self-reinforcing boom-bust cycles that trend far beyond fundamentals before eventually reversing. The framework looks for situations where a feedback loop has been established — where rising prices are improving fundamentals (or vice versa) in a way the market has not yet fully priced. At the macro level, this involves currency dynamics, credit expansion/contraction, and policy responses. The framework does not predict a fixed outcome but rather identifies the prevailing trend and rides it until signs of reversal emerge. Position sizing is aggressive when the thesis is clear; the framework accepts being wrong early rather than missing the major move. This is an educational application of Soros' publicly documented philosophy, not affiliated with or endorsed by Soros or Soros Fund Management.`,
    rules: [
      { id: 'reflexivity', label: 'Reflexivity Setup', description: 'Market perception is measurably affecting the underlying fundamentals, creating a feedback loop' },
      { id: 'trend_direction', label: 'Trend Identification', description: 'Prevailing trend is clearly established and participants are still positioned in the same direction' },
      { id: 'macro_catalyst', label: 'Macro Catalyst', description: 'Policy decision, currency movement, or credit event is the identifiable trigger' },
      { id: 'reversal_absent', label: 'No Reversal Signal Yet', description: 'No credible sign that the feedback loop is close to breaking down' },
      { id: 'asymmetric_loss', label: 'Controlled Downside', description: 'Position can be sized so that being wrong early does not cause permanent capital damage' },
      { id: 'liquidity', label: 'Market Liquidity', description: 'Market is liquid enough to scale position and exit rapidly if conditions change' },
    ],
    equations: [
      { label: 'Reflexivity Gauge', formula: 'Rate of change of fundamentals driven by market prices ÷ baseline fundamental change rate' },
      { label: 'Expected Value', formula: 'Σ (Probability of scenario × Return in scenario)' },
    ],
  },

  {
    id: 'ackman',
    name: 'Bill Ackman',
    shortName: 'Ackman',
    era: '2004–present',
    style: 'Concentrated Activist Value',
    tagline: 'Simple, predictable, cash-generative businesses at a discount',
    avatar: 'BA',
    color: '#7c3aed',
    ctx: `Apply Bill Ackman's concentrated activist value framework as documented through Pershing Square Capital Management's investor letters, public presentations, and interviews. The framework seeks a small number of high-conviction investments — typically 8–15 positions — in simple, predictable, free-cash-flow-generative businesses trading at a meaningful discount to intrinsic value. A key differentiator is the activist dimension: Ackman's framework explicitly looks for businesses where operational, financial, or strategic changes under management pressure could unlock significant additional value. Target companies must have durable brands or market positions, pricing power, and recurring revenue. The framework avoids complex businesses, commodity producers, and situations where the thesis requires predicting macro outcomes. Concentration is a feature, not a bug — mistakes are acknowledged quickly and positions are exited. This is an educational application of Ackman's publicly documented philosophy, not affiliated with or endorsed by Ackman or Pershing Square.`,
    rules: [
      { id: 'simple_predictable', label: 'Simple & Predictable Business', description: 'Business model generates reliable, recurring free cash flow with minimal complexity' },
      { id: 'durable_brand', label: 'Durable Brand or Market Position', description: 'Company has a consumer brand or market position that is difficult to displace' },
      { id: 'pricing_power', label: 'Pricing Power', description: 'Company can raise prices at or above inflation without significant volume loss' },
      { id: 'activist_lever', label: 'Activist Catalyst Available', description: 'Identifiable operational, capital structure, or strategic change that management or a new CEO could execute to unlock value' },
      { id: 'discount_intrinsic', label: 'Discount to Intrinsic Value', description: 'Current price represents at least 30% discount to conservative intrinsic value estimate' },
      { id: 'low_capex', label: 'Low Capital Intensity', description: 'Business requires minimal ongoing capital expenditure to maintain its competitive position' },
    ],
    equations: [
      { label: 'Intrinsic Value (DCF)', formula: 'Σ (FCF_t ÷ (1 + r)^t) + Terminal Value' },
      { label: 'Activist Upside', formula: 'Intrinsic Value post-improvement − Current Market Cap' },
    ],
  },

  {
    id: 'burry',
    name: 'Michael Burry',
    shortName: 'Burry',
    era: '2000–present',
    style: 'Deep Contrarian / Statistical Value',
    tagline: 'Find what everyone is ignoring — then check the balance sheet',
    avatar: 'MB',
    color: '#dc2626',
    ctx: `Apply Michael Burry's deep contrarian value framework as documented through his value investing message board posts (early career), Scion Capital letters, and public interviews. Burry's approach begins with statistical screens: low EV/EBIT, low P/FCF, and low EV/Sales across sectors that are deeply out of favour or misunderstood. The framework requires original, bottom-up due diligence that goes beyond consensus analysis — reading every footnote, understanding the accounting, and stress-testing the balance sheet. A critical element is the identification of a specific, articulable reason why the market narrative about this stock is wrong. Burry is particularly attentive to accounting quality, off-balance-sheet liabilities, and cash flow vs. reported earnings discrepancies. The framework is not sector-constrained and has a high tolerance for illiquid, ugly, or controversial situations. This is an educational application of Burry's publicly documented philosophy, not affiliated with or endorsed by Burry or Scion Asset Management.`,
    rules: [
      { id: 'ev_ebit', label: 'Low EV/EBIT', description: 'EV/EBIT below 10× — getting significant operating earnings for the enterprise price paid' },
      { id: 'fcf_yield', label: 'High FCF Yield', description: 'Free cash flow yield above 8% — company generates real cash not just accounting earnings' },
      { id: 'balance_sheet', label: 'Solid Balance Sheet', description: 'Net debt is manageable; no risk of dilutive capital raise or bankruptcy in a downturn' },
      { id: 'accounting_quality', label: 'Clean Accounting', description: 'Reported earnings are supported by operating cash flow; no unusual accruals or off-balance-sheet items' },
      { id: 'wrong_narrative', label: 'Wrong Market Narrative', description: 'Specific, articulable reason why the market consensus view on this stock is factually incorrect' },
      { id: 'out_of_favour', label: 'Out of Favour Sector', description: 'Sector is experiencing maximum pessimism, creating valuation opportunities across the cohort' },
    ],
    equations: [
      { label: 'EV/EBIT', formula: 'Enterprise Value ÷ EBIT (trailing twelve months)' },
      { label: 'FCF Yield', formula: 'Free Cash Flow ÷ Market Capitalisation' },
    ],
  },

  {
    id: 'smith',
    name: 'Terry Smith',
    shortName: 'T. Smith',
    era: '2010–present',
    style: 'Quality Compounder / Buy & Hold',
    tagline: 'Buy good companies, don\'t overpay, do nothing',
    avatar: 'TS',
    color: '#16a34a',
    ctx: `Apply Terry Smith's quality compounder framework as documented through Fundsmith Equity Fund annual letters and his book Investing for Growth. The philosophy is deliberately simple: buy high-quality businesses, avoid paying too much for them, and then do nothing — long holding periods compound returns. Quality is defined primarily by return on capital employed (ROCE) above 20%, strong and stable free cash flow conversion from earnings, minimal need for external capital to grow, and genuine pricing power. Smith explicitly avoids businesses that require high leverage to generate returns, commodity businesses with no pricing power, and companies that grow primarily through debt-funded acquisitions. The framework is sector-agnostic but strongly skews toward branded consumer goods, healthcare products, and software — businesses with repeat purchase dynamics. Valuation discipline matters: the framework will not buy even a high-quality business at an excessive premium. This is an educational application of Smith's publicly documented philosophy, not affiliated with or endorsed by Smith or Fundsmith.`,
    rules: [
      { id: 'roce', label: 'ROCE > 20%', description: 'Return on capital employed consistently above 20% — high returns on incremental reinvestment' },
      { id: 'fcf_conversion', label: 'High FCF Conversion', description: 'Free cash flow conversion from reported earnings above 80% — earnings are real cash' },
      { id: 'no_external_capital', label: 'Self-Funding Growth', description: 'Business funds its own growth from operating cash flow without regular equity issuance or leverage' },
      { id: 'pricing_power', label: 'Pricing Power', description: 'Proven ability to raise prices ahead of cost inflation without volume deterioration' },
      { id: 'repeat_purchase', label: 'Repeat Purchase Dynamic', description: 'Customers buy repeatedly — subscription, consumable, or habitual purchase model' },
      { id: 'fair_valuation', label: 'Not Significantly Overvalued', description: 'FCF yield or earnings yield is not so compressed that returns are mathematically impaired for a decade' },
    ],
    equations: [
      { label: 'ROCE', formula: 'EBIT ÷ (Total Assets − Current Liabilities)' },
      { label: 'FCF Conversion', formula: 'Free Cash Flow ÷ Net Income' },
    ],
  },

  {
    id: 'einhorn',
    name: 'David Einhorn',
    shortName: 'Einhorn',
    era: '1996–present',
    style: 'Long/Short Deep Value',
    tagline: 'The market eventually corrects when the fundamentals are undeniable',
    avatar: 'DE',
    color: '#9333ea',
    ctx: `Apply David Einhorn's long/short deep-value framework as documented through Greenlight Capital investor letters, Fooling Some of the People All of the Time, and public presentations. The framework is built on rigorous fundamental analysis that goes beyond consensus — constructing an independent earnings model and identifying where the market's assumptions are provably wrong. On the long side, the framework seeks businesses trading at a significant discount to intrinsic value with a specific catalyst, clean accounting, and management that acts in shareholders' interests. On the short side, the framework looks for businesses with deteriorating fundamentals, accounting irregularities, or structural industry declines where the market has not yet updated its view. Earnings quality analysis is a hallmark: Einhorn specifically checks whether reported EPS is supported by free cash flow. Management credibility and capital allocation track record are given significant weight. This is an educational application of Einhorn's publicly documented philosophy, not affiliated with or endorsed by Einhorn or Greenlight Capital.`,
    rules: [
      { id: 'earnings_quality', label: 'Earnings Quality', description: 'Reported EPS is supported by operating free cash flow — no large accruals masking deteriorating cash generation' },
      { id: 'independent_model', label: 'Independent Valuation Model', description: 'Proprietary earnings model reaches a materially different conclusion from sell-side consensus' },
      { id: 'wrong_consensus', label: 'Identifiable Consensus Error', description: 'Specific, factual reason why the Street\'s earnings or growth assumptions are incorrect' },
      { id: 'catalyst', label: 'Value Catalyst', description: 'Identifiable event — earnings beat, asset sale, management change — that will force rerating' },
      { id: 'mgmt_credibility', label: 'Management Credibility', description: 'Management has a track record of honest communication and shareholder-aligned capital allocation' },
      { id: 'discount_to_iv', label: 'Meaningful Discount', description: 'Stock trades at a material discount to independently derived intrinsic value' },
    ],
    equations: [
      { label: 'Earnings Quality Ratio', formula: 'Operating Cash Flow ÷ Net Income (should be ≥ 1.0)' },
      { label: 'Owner Earnings', formula: 'Net Income + D&A − Maintenance CapEx − Working Capital Change' },
    ],
  },

  {
    id: 'miller',
    name: 'Bill Miller',
    shortName: 'Miller',
    era: '1982–present',
    style: 'Contrarian Value / Expected Value',
    tagline: 'Every asset has a price at which it becomes a value investment',
    avatar: 'BM',
    color: '#ea580c',
    ctx: `Apply Bill Miller's contrarian value framework as documented through Legg Mason Capital Management letters and his public interviews. Miller's famous 15-consecutive-year S&P 500 outperformance was built on an expected-value approach: assessing probability-weighted scenarios across bull, base, and bear cases, then buying when the expected value substantially exceeds the current price. A defining characteristic is willingness to invest in businesses that traditional value metrics label as "expensive" — Miller argued that what looks expensive on backward-looking metrics can be cheap on forward intrinsic value. He famously bought Amazon and other early technology companies when value investors avoided them. The framework emphasises mean reversion as a powerful force — hated, ignored sectors and stocks often recover when fundamentals stabilise. Competitive dynamics, business model evolution, and whether the market is pricing in permanent impairment vs. temporary distress are key analytical questions. This is an educational application of Miller's publicly documented philosophy, not affiliated with or endorsed by Miller or Miller Value Partners.`,
    rules: [
      { id: 'expected_value', label: 'Positive Expected Value', description: 'Probability-weighted across bull/base/bear scenarios, expected return substantially exceeds current price' },
      { id: 'mean_reversion', label: 'Mean Reversion Candidate', description: 'Fundamentals are temporarily depressed and reversion to normalised returns is plausible' },
      { id: 'iv_vs_price', label: 'Intrinsic Value Exceeds Price', description: 'Forward intrinsic value is meaningfully above current price even if backward metrics look expensive' },
      { id: 'competitive_position', label: 'Durable Competitive Position', description: 'Business is not in permanent structural decline — competitive advantages are intact despite temporary headwinds' },
      { id: 'hated_sector', label: 'Contrarian Setup', description: 'Sector or stock is widely disliked or ignored, creating pricing inefficiency' },
      { id: 'not_permanent', label: 'No Permanent Impairment', description: 'Market is pricing in permanent impairment where analysis shows only temporary distress' },
    ],
    equations: [
      { label: 'Expected Value', formula: 'Σ (P_scenario × Return_scenario) across all identified scenarios' },
      { label: 'Normalised P/E', formula: 'Current Price ÷ Normalised EPS (mid-cycle earnings estimate)' },
    ],
  },

  {
    id: 'watsa',
    name: 'Prem Watsa',
    shortName: 'Watsa',
    era: '1985–present',
    style: 'Value with Macro Hedging',
    tagline: 'Protect the downside; the upside takes care of itself',
    avatar: 'PW',
    color: '#b45309',
    ctx: `Apply Prem Watsa's value-with-macro-hedging investment framework as documented through Fairfax Financial Holdings annual reports and shareholder letters. Known as "Canada's Buffett," Watsa combines classic bottom-up value investing with top-down macro risk management — a combination inspired by both Buffett and his reading of the 1930s Depression. The framework seeks deeply undervalued companies with strong balance sheets, capable management, and identifiable catalysts. Simultaneously, it assesses macro risks — deflation, credit contraction, geopolitical risk — that could permanently impair value regardless of company fundamentals. The insurance float model is central: Fairfax's investment approach leverages insurance premium float to buy undervalued assets, so capital efficiency is explicitly valued. Distressed debt and special situations are within the framework's scope. The framework has a strong emphasis on avoiding permanent capital loss even at the cost of some upside participation. This is an educational application of Watsa's publicly documented philosophy, not affiliated with or endorsed by Watsa or Fairfax Financial.`,
    rules: [
      { id: 'deep_value', label: 'Deep Value Metrics', description: 'Trades at a significant discount to book value or asset value with clean balance sheet' },
      { id: 'macro_resilience', label: 'Macro Resilience', description: 'Business can survive a severe deflationary or recessionary scenario without permanent impairment' },
      { id: 'mgmt_ownership', label: 'Management Ownership', description: 'Management has significant personal capital at stake alongside public shareholders' },
      { id: 'catalyst', label: 'Value Catalyst', description: 'Identifiable event that will cause the market to recognise intrinsic value within a reasonable timeframe' },
      { id: 'balance_sheet', label: 'Strong Balance Sheet', description: 'Company is not at risk of equity dilution or bankruptcy under stress scenarios' },
      { id: 'no_perm_loss', label: 'No Permanent Loss Scenario', description: 'Even in a pessimistic macro scenario, capital is not permanently impaired' },
    ],
    equations: [
      { label: 'Price to Book', formula: 'Market Price ÷ Book Value Per Share' },
      { label: 'Float Yield', formula: 'Investment Income ÷ Average Float Outstanding (for insurance cos)' },
    ],
  },

  {
    id: 'lilu',
    name: 'Li Lu',
    shortName: 'Li Lu',
    era: '1997–present',
    style: 'Quality Value / Concentrated Global',
    tagline: 'Find a genuinely exceptional business and hold it forever',
    avatar: 'LL',
    color: '#4f46e5',
    ctx: `Apply Li Lu's quality-concentrated value framework as documented through his Himalaya Capital letters, published essays, and interviews, including his foreword to Poor Charlie's Almanack. Li Lu's philosophy is the most direct synthesis of Buffett and Munger principles applied with a global perspective — particularly deep knowledge of Chinese and Asian markets. The framework demands that a business be genuinely exceptional: durable competitive advantages, honest and capable management, long runway for compounding, and a price that does not fully reflect the long-term value. Li Lu places exceptional emphasis on the quality of management — their integrity, capital allocation skill, and alignment with minority shareholders — viewing this as the most important factor, particularly in markets where governance standards are lower. The framework is highly concentrated: only businesses fully understood and deeply convicted on are held. Political and regulatory risk is explicitly assessed as part of the investment thesis. This is an educational application of Li Lu's publicly documented philosophy, not affiliated with or endorsed by Li Lu or Himalaya Capital.`,
    rules: [
      { id: 'exceptional_business', label: 'Genuinely Exceptional Business', description: 'Business has durable, structural competitive advantages — not merely good execution in a commoditised industry' },
      { id: 'mgmt_integrity', label: 'Management Integrity & Skill', description: 'Management team is honest, capable, and has a long track record of rational capital allocation' },
      { id: 'long_runway', label: 'Long Compounding Runway', description: 'Large addressable market and reinvestment opportunities will allow the business to compound for 10–20+ years' },
      { id: 'political_risk', label: 'Political Risk Assessed', description: 'Regulatory and political risk to the business model is explicitly understood and priced in' },
      { id: 'alignment', label: 'Minority Shareholder Alignment', description: 'Governance structure protects minority shareholders; no history of value transfer to controlling interests' },
      { id: 'price_reasonable', label: 'Reasonable Valuation', description: 'Valuation does not require heroic assumptions to generate acceptable long-term returns' },
    ],
    equations: [
      { label: 'Owner Earnings', formula: 'Net Income + D&A − Maintenance CapEx − Working Capital Change' },
      { label: 'Intrinsic Value Growth', formula: 'IV = Owner Earnings × (1 + g) ÷ (r − g) where g = sustainable reinvestment rate × ROCE' },
    ],
  },

  {
    id: 'schloss',
    name: 'Walter Schloss',
    shortName: 'Schloss',
    era: '1955–2002',
    style: 'Classic Deep Value / Graham Disciple',
    tagline: 'Buy bargains — the numbers don\'t lie',
    avatar: 'WS',
    color: '#64748b',
    ctx: `Apply Walter Schloss' classic deep value framework as documented through his WJS Limited Partners letters and interviews. Schloss was a direct student of Benjamin Graham and ran one of the most consistent long-term track records in investment history — 28.7% gross annual returns over 47 years — using a purely quantitative, balance-sheet-focused approach. The framework requires no management meetings, no earnings calls, and no elaborate business analysis. It seeks stocks trading below book value with manageable debt, often near 52-week or multi-year lows, with some insider buying as confirmation. Schloss held a large number of positions (100+ at times) to diversify individual security risk. The framework is explicitly not about finding great businesses — it is about finding statistically cheap ones with enough asset backing that permanent loss is unlikely. Patience is a core requirement: positions may be held for 4–5 years waiting for value to be realised. This is an educational application of Schloss' publicly documented philosophy, not affiliated with or endorsed by the Schloss family.`,
    rules: [
      { id: 'below_book', label: 'Price Below Book Value', description: 'Stock price is below book value per share — buying $1 of net assets for less than $1' },
      { id: 'low_debt', label: 'Low or No Long-Term Debt', description: 'Long-term debt is low relative to equity — balance sheet strength prevents forced dilution' },
      { id: '52w_low', label: 'Near Multi-Year Low', description: 'Stock is near its 52-week or multi-year low — pessimism is already priced in' },
      { id: 'insider_buying', label: 'Insider Buying Present', description: 'Company insiders (directors, officers) have purchased shares on the open market recently' },
      { id: 'not_losing_money', label: 'Not Losing Money Consistently', description: 'Company is not burning cash at a rate that will consume book value before recovery' },
      { id: 'tangible_assets', label: 'Tangible Asset Backing', description: 'Book value is primarily tangible assets (receivables, inventory, property) not goodwill' },
    ],
    equations: [
      { label: 'Price to Book', formula: 'Market Price ÷ (Total Assets − Intangibles − Total Liabilities)' },
      { label: 'Net Current Asset Value', formula: 'Current Assets − Total Liabilities (Graham\'s NCAV)' },
    ],
  },

  {
    id: 'templeton',
    name: 'John Templeton',
    shortName: 'Templeton',
    era: '1954–2001',
    style: 'Global Contrarian Value',
    tagline: 'Buy at the point of maximum pessimism',
    avatar: 'JT',
    color: '#0891b2',
    ctx: `Apply John Templeton's global contrarian value framework as documented through his Templeton Growth Fund annual reports, authorized biographies, and interviews. Templeton pioneered global diversification at a time when most investors focused exclusively on the United States, and his core insight — that the best bargains are found where pessimism is greatest — remains one of the most durable principles in value investing. The framework actively seeks the most hated, ignored, and feared markets, sectors, and stocks, asking whether the pessimism is justified by the actual long-term fundamentals. Templeton normalised earnings across full business cycles to avoid being fooled by cyclical peaks or troughs. The framework is explicitly global: the best value may be in any country at any given time, and geographic concentration is viewed as an unnecessary constraint. A deeply spiritual investor, Templeton also weighted management character and ethical behaviour as investment factors. This is an educational application of Templeton's publicly documented philosophy, not affiliated with or endorsed by the Templeton estate or Franklin Templeton.`,
    rules: [
      { id: 'max_pessimism', label: 'Maximum Pessimism Present', description: 'Stock, sector, or market is at or near peak negative sentiment — institutional and media coverage is overwhelmingly negative' },
      { id: 'normalised_pe', label: 'Low Normalised P/E', description: 'Price is low relative to normalised (mid-cycle) earnings — not just cyclically depressed trough earnings' },
      { id: 'global_relative_value', label: 'Cheap vs Global Peers', description: 'Valuation is attractive relative to comparable companies globally, not just within the domestic market' },
      { id: 'justified_pessimism', label: 'Pessimism Not Fully Justified', description: 'Specific analysis shows the consensus negativity overstates the long-term impairment to earnings power' },
      { id: 'mgmt_character', label: 'Management Character', description: 'Management has a track record of honest dealing and has not enriched themselves at shareholders\' expense' },
      { id: 'diversification', label: 'Global Diversification Considered', description: 'Opportunity is assessed in the context of global alternatives — is this the best value available anywhere?' },
    ],
    equations: [
      { label: 'Normalised P/E', formula: 'Current Price ÷ Average EPS over a full business cycle (7–10 years)' },
      { label: 'Global Relative Value', formula: 'Company P/E ÷ Median P/E of global sector peers' },
    ],
  },
]

export const INV: Record<string, Investor> = Object.fromEntries(
  INVESTORS.map((inv) => [inv.id, inv])
)
