import type { Stock } from '../types'

export const STOCKS: Stock[] = [
  // ── Technology ────────────────────────────────────────────────────────────
  { ticker: 'AAPL',  name: 'Apple Inc.',                  sector: 'Technology',             description: 'Consumer electronics, software, and services ecosystem with iconic brand and massive installed base.' },
  { ticker: 'MSFT',  name: 'Microsoft Corporation',        sector: 'Technology',             description: 'Cloud computing (Azure), productivity software (Office 365), and enterprise solutions.' },
  { ticker: 'NVDA',  name: 'NVIDIA Corporation',           sector: 'Technology',             description: 'GPU leader powering AI training and inference, data centres, gaming, and autonomous vehicles.' },
  { ticker: 'AVGO',  name: 'Broadcom Inc.',                sector: 'Technology',             description: 'Semiconductor and infrastructure software company serving cloud, networking, and broadband markets.' },
  { ticker: 'ORCL',  name: 'Oracle Corporation',           sector: 'Technology',             description: 'Enterprise database, cloud applications, and infrastructure services for large organisations.' },
  { ticker: 'ADBE',  name: 'Adobe Inc.',                   sector: 'Technology',             description: 'Creative software (Photoshop, Illustrator) and digital marketing SaaS platform.' },
  { ticker: 'CRM',   name: 'Salesforce Inc.',              sector: 'Technology',             description: 'World\'s leading CRM platform with cloud-based sales, service, and marketing tools.' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices',       sector: 'Technology',             description: 'High-performance CPUs and GPUs for data centres, gaming PCs, and embedded systems.' },
  { ticker: 'INTC',  name: 'Intel Corporation',            sector: 'Technology',             description: 'Largest x86 chip maker undergoing a major foundry and product transformation.' },
  { ticker: 'QCOM',  name: 'Qualcomm Inc.',                sector: 'Technology',             description: 'Mobile processor and modem leader with strong IP licensing business in smartphones and IoT.' },
  { ticker: 'TXN',   name: 'Texas Instruments Inc.',       sector: 'Technology',             description: 'Analog and embedded processing chips for industrial, automotive, and personal electronics.' },
  { ticker: 'AMAT',  name: 'Applied Materials Inc.',       sector: 'Technology',             description: 'Semiconductor equipment and services used by chipmakers worldwide.' },
  { ticker: 'INTU',  name: 'Intuit Inc.',                  sector: 'Technology',             description: 'Financial software for consumers and SMBs including TurboTax, QuickBooks, and Credit Karma.' },
  { ticker: 'NOW',   name: 'ServiceNow Inc.',              sector: 'Technology',             description: 'Cloud workflow automation platform for IT, HR, and customer service operations.' },
  { ticker: 'PANW',  name: 'Palo Alto Networks',           sector: 'Technology',             description: 'Cybersecurity platform covering network, cloud, and endpoint security with AI-driven operations.' },
  { ticker: 'SNPS',  name: 'Synopsys Inc.',                sector: 'Technology',             description: 'Electronic design automation software and IP essential for chip design.' },
  { ticker: 'CDNS',  name: 'Cadence Design Systems',       sector: 'Technology',             description: 'EDA tools and IP for semiconductor and systems design used by top chipmakers.' },
  { ticker: 'KLAC',  name: 'KLA Corporation',              sector: 'Technology',             description: 'Process control and inspection equipment critical to semiconductor manufacturing yield.' },
  { ticker: 'LRCX',  name: 'Lam Research Corporation',    sector: 'Technology',             description: 'Wafer fabrication equipment for memory and logic chip production.' },
  { ticker: 'MU',    name: 'Micron Technology',            sector: 'Technology',             description: 'DRAM and NAND flash memory chips used in PCs, servers, mobile, and automotive.' },
  { ticker: 'CSCO',  name: 'Cisco Systems Inc.',           sector: 'Technology',             description: 'Networking hardware and software powering enterprise and service-provider infrastructure.' },
  { ticker: 'IBM',   name: 'IBM Corporation',              sector: 'Technology',             description: 'Hybrid cloud, AI consulting, and mainframe services for enterprise customers.' },
  { ticker: 'ACN',   name: 'Accenture plc',                sector: 'Technology',             description: 'Global IT consulting and outsourcing firm with broad digital transformation services.' },
  { ticker: 'FICO',  name: 'Fair Isaac Corporation',       sector: 'Technology',             description: 'Creator of the FICO credit score with analytics software for financial services.' },
  { ticker: 'FTNT',  name: 'Fortinet Inc.',                sector: 'Technology',             description: 'Network security appliances and cloud security services for enterprises.' },
  { ticker: 'WDAY',  name: 'Workday Inc.',                 sector: 'Technology',             description: 'Cloud-based human capital management and financial management SaaS for large enterprises.' },
  { ticker: 'SHOP',  name: 'Shopify Inc.',                 sector: 'Technology',             description: 'E-commerce platform empowering millions of merchants with storefronts, payments, and logistics.' },
  { ticker: 'SNOW',  name: 'Snowflake Inc.',               sector: 'Technology',             description: 'Cloud data warehousing and analytics platform with a consumption-based revenue model.' },
  { ticker: 'PLTR',  name: 'Palantir Technologies',        sector: 'Technology',             description: 'Data analytics and AI software for government intelligence and commercial enterprises.' },
  { ticker: 'RBLX',  name: 'Roblox Corporation',           sector: 'Technology',             description: 'Online gaming and metaverse platform with 80M+ daily active users.' },
  { ticker: 'TTD',   name: 'The Trade Desk Inc.',          sector: 'Technology',             description: 'Demand-side programmatic advertising platform for digital marketers.' },

  // ── Communication Services ─────────────────────────────────────────────────
  { ticker: 'GOOGL', name: 'Alphabet Inc.',                sector: 'Communication Services', description: 'Search advertising dominance, YouTube, Google Cloud, and a portfolio of moonshot bets.' },
  { ticker: 'META',  name: 'Meta Platforms Inc.',          sector: 'Communication Services', description: 'Social media empire (Facebook, Instagram, WhatsApp) with growing AI and AR/VR investments.' },
  { ticker: 'NFLX',  name: 'Netflix Inc.',                 sector: 'Communication Services', description: 'Global streaming leader with 260M+ subscribers and expanding into live events and gaming.' },
  { ticker: 'DIS',   name: 'The Walt Disney Company',      sector: 'Communication Services', description: 'Entertainment conglomerate with theme parks, studios, Disney+, and ESPN.' },
  { ticker: 'CMCSA', name: 'Comcast Corporation',          sector: 'Communication Services', description: 'Cable, internet, NBCUniversal media, and Sky broadcasting operations.' },
  { ticker: 'T',     name: 'AT&T Inc.',                    sector: 'Communication Services', description: 'US wireless carrier and fiber broadband provider with a heavy debt load.' },
  { ticker: 'VZ',    name: 'Verizon Communications',       sector: 'Communication Services', description: 'Largest US wireless network operator with consumer and enterprise segments.' },
  { ticker: 'TMUS',  name: 'T-Mobile US Inc.',             sector: 'Communication Services', description: 'Fast-growing US wireless carrier with 5G leadership following the Sprint merger.' },
  { ticker: 'WBD',   name: 'Warner Bros. Discovery',       sector: 'Communication Services', description: 'Media conglomerate operating CNN, HBO, Warner Bros. studios, and Max streaming.' },
  { ticker: 'SPOT',  name: 'Spotify Technology',           sector: 'Communication Services', description: 'World\'s largest music and podcast streaming platform with 600M+ users.' },

  // ── Consumer Discretionary ─────────────────────────────────────────────────
  { ticker: 'AMZN',  name: 'Amazon.com Inc.',              sector: 'Consumer Discretionary', description: 'E-commerce, cloud computing (AWS), advertising, and logistics — multiple platform businesses.' },
  { ticker: 'TSLA',  name: 'Tesla Inc.',                   sector: 'Consumer Discretionary', description: 'Electric vehicle pioneer with energy storage, solar, and an autonomous driving platform.' },
  { ticker: 'HD',    name: 'The Home Depot Inc.',          sector: 'Consumer Discretionary', description: 'Largest home improvement retailer with ~2,300 stores across North America.' },
  { ticker: 'MCD',   name: 'McDonald\'s Corporation',      sector: 'Consumer Discretionary', description: 'Global fast-food franchise with 40,000+ locations and a capital-light royalty model.' },
  { ticker: 'NKE',   name: 'Nike Inc.',                    sector: 'Consumer Discretionary', description: 'World\'s largest athletic footwear and apparel brand with strong direct-to-consumer shift.' },
  { ticker: 'SBUX',  name: 'Starbucks Corporation',        sector: 'Consumer Discretionary', description: 'Global coffeehouse chain with 36,000+ stores and a loyalty-driven revenue model.' },
  { ticker: 'LOW',   name: 'Lowe\'s Companies Inc.',       sector: 'Consumer Discretionary', description: 'Second-largest home improvement retailer focused on Pro customers and digital growth.' },
  { ticker: 'BKNG',  name: 'Booking Holdings Inc.',        sector: 'Consumer Discretionary', description: 'Online travel agency operating Booking.com, Priceline, Kayak, and OpenTable.' },
  { ticker: 'TGT',   name: 'Target Corporation',           sector: 'Consumer Discretionary', description: 'Mass-market retailer with owned brands, same-day fulfilment, and loyal loyalty programme.' },
  { ticker: 'CMG',   name: 'Chipotle Mexican Grill',       sector: 'Consumer Discretionary', description: 'Fast-casual Mexican restaurant chain with strong unit economics and digital order growth.' },
  { ticker: 'ABNB',  name: 'Airbnb Inc.',                  sector: 'Consumer Discretionary', description: 'Online marketplace for short-term lodging and experiences in 220+ countries.' },
  { ticker: 'UBER',  name: 'Uber Technologies Inc.',       sector: 'Consumer Discretionary', description: 'Ride-hailing and food delivery platform with growing freight and autonomous vehicle ambitions.' },
  { ticker: 'LYFT',  name: 'Lyft Inc.',                    sector: 'Consumer Discretionary', description: 'US ride-hailing platform competing with Uber, focused on profitability improvement.' },
  { ticker: 'EBAY',  name: 'eBay Inc.',                    sector: 'Consumer Discretionary', description: 'Online marketplace for new and used goods with a focus on collectibles and niche categories.' },
  { ticker: 'F',     name: 'Ford Motor Company',           sector: 'Consumer Discretionary', description: 'Legacy automaker investing heavily in EVs (F-150 Lightning, Mustang Mach-E) via Ford Model e.' },
  { ticker: 'GM',    name: 'General Motors Company',       sector: 'Consumer Discretionary', description: 'US automaker transitioning to EVs with Ultium platform and Cruise autonomous driving unit.' },
  { ticker: 'RIVN',  name: 'Rivian Automotive',            sector: 'Consumer Discretionary', description: 'EV startup making pickup trucks and SUVs with Amazon delivery vans as a key anchor customer.' },

  // ── Consumer Staples ──────────────────────────────────────────────────────
  { ticker: 'KO',    name: 'The Coca-Cola Company',        sector: 'Consumer Staples',       description: 'Global beverage giant with unparalleled brand recognition and distribution network.' },
  { ticker: 'PG',    name: 'Procter & Gamble Co.',         sector: 'Consumer Staples',       description: 'Consumer goods giant with household brands across cleaning, beauty, and personal care.' },
  { ticker: 'WMT',   name: 'Walmart Inc.',                 sector: 'Consumer Staples',       description: 'World\'s largest retailer with massive scale advantages, growing e-commerce and advertising.' },
  { ticker: 'COST',  name: 'Costco Wholesale Corporation', sector: 'Consumer Staples',       description: 'Membership warehouse club with exceptional customer loyalty and pricing power.' },
  { ticker: 'PEP',   name: 'PepsiCo Inc.',                 sector: 'Consumer Staples',       description: 'Beverages and snack foods (Frito-Lay, Quaker) with a highly diversified product portfolio.' },
  { ticker: 'PM',    name: 'Philip Morris International',  sector: 'Consumer Staples',       description: 'Tobacco and smoke-free products company transitioning to IQOS heated tobacco globally.' },
  { ticker: 'MO',    name: 'Altria Group Inc.',            sector: 'Consumer Staples',       description: 'US tobacco leader (Marlboro) with substantial dividend yield and oral tobacco optionality.' },
  { ticker: 'MDLZ',  name: 'Mondelez International',       sector: 'Consumer Staples',       description: 'Global snacking powerhouse with brands like Oreo, Cadbury, and Toblerone.' },
  { ticker: 'CL',    name: 'Colgate-Palmolive Company',    sector: 'Consumer Staples',       description: 'Oral care, personal care, and home care brands sold in 200+ countries.' },
  { ticker: 'GIS',   name: 'General Mills Inc.',           sector: 'Consumer Staples',       description: 'Consumer food company with Cheerios, Haagen-Dazs, Blue Buffalo pet food and more.' },
  { ticker: 'KHC',   name: 'The Kraft Heinz Company',      sector: 'Consumer Staples',       description: 'Packaged food and beverage company with Heinz, Kraft, Oscar Mayer, and Philadelphia brands.' },

  // ── Healthcare ────────────────────────────────────────────────────────────
  { ticker: 'JNJ',   name: 'Johnson & Johnson',            sector: 'Healthcare',             description: 'Diversified healthcare company spanning pharmaceuticals, MedTech devices, and consumer health.' },
  { ticker: 'LLY',   name: 'Eli Lilly and Company',        sector: 'Healthcare',             description: 'Pharmaceutical company with blockbuster GLP-1 drugs (Mounjaro, Zepbound) for diabetes and obesity.' },
  { ticker: 'UNH',   name: 'UnitedHealth Group Inc.',      sector: 'Healthcare',             description: 'Largest US health insurer with UnitedHealthcare plans and Optum health services.' },
  { ticker: 'ABBV',  name: 'AbbVie Inc.',                  sector: 'Healthcare',             description: 'Biopharmaceutical company with Humira, Skyrizi, and Rinvoq immunology drugs.' },
  { ticker: 'MRK',   name: 'Merck & Co. Inc.',             sector: 'Healthcare',             description: 'Global pharma company with Keytruda oncology drug and vaccines including Gardasil.' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific',     sector: 'Healthcare',             description: 'Life sciences tools and instruments enabling scientific research, diagnostics, and drug development.' },
  { ticker: 'ABT',   name: 'Abbott Laboratories',          sector: 'Healthcare',             description: 'Medical devices, diagnostics, nutrition products, and branded generic pharmaceuticals.' },
  { ticker: 'DHR',   name: 'Danaher Corporation',          sector: 'Healthcare',             description: 'Life sciences and diagnostics instruments with a proven acquisition and operational excellence model.' },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb',         sector: 'Healthcare',             description: 'Oncology-focused pharma with Opdivo, Revlimid, and Eliquis among key drugs.' },
  { ticker: 'AMGN',  name: 'Amgen Inc.',                   sector: 'Healthcare',             description: 'Biotechnology pioneer in inflammation, oncology, and cardiovascular rare diseases.' },
  { ticker: 'GILD',  name: 'Gilead Sciences Inc.',         sector: 'Healthcare',             description: 'Antiviral specialist with HIV (Biktarvy) and hepatitis C treatments plus oncology pipeline.' },
  { ticker: 'ISRG',  name: 'Intuitive Surgical Inc.',      sector: 'Healthcare',             description: 'Leader in robotic-assisted surgery with the da Vinci surgical system.' },
  { ticker: 'SYK',   name: 'Stryker Corporation',          sector: 'Healthcare',             description: 'Medical devices company specialising in orthopaedic implants, surgical equipment, and neurotechnology.' },
  { ticker: 'BSX',   name: 'Boston Scientific Corporation',sector: 'Healthcare',             description: 'Medical devices for interventional cardiology, urology, endoscopy, and neuromodulation.' },
  { ticker: 'CVS',   name: 'CVS Health Corporation',       sector: 'Healthcare',             description: 'Integrated health services including pharmacies, Aetna insurance, and MinuteClinic.' },
  { ticker: 'CI',    name: 'The Cigna Group',              sector: 'Healthcare',             description: 'Global health services company with Evernorth pharmacy and Cigna Healthcare insurance.' },
  { ticker: 'HUM',   name: 'Humana Inc.',                  sector: 'Healthcare',             description: 'Health insurance focused on Medicare Advantage plans with CenterWell primary care.' },
  { ticker: 'REGN',  name: 'Regeneron Pharmaceuticals',    sector: 'Healthcare',             description: 'Biotechnology company with Eylea, Dupixent, and Kevzara among approved treatments.' },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals',       sector: 'Healthcare',             description: 'Leader in cystic fibrosis treatments with Trikafta and a growing pain and kidney pipeline.' },

  // ── Financials ────────────────────────────────────────────────────────────
  { ticker: 'BRK.B', name: 'Berkshire Hathaway',           sector: 'Financials',             description: 'Diversified holding company with wholly-owned businesses and large equity portfolio managed by Buffett.' },
  { ticker: 'JPM',   name: 'JPMorgan Chase & Co.',         sector: 'Financials',             description: 'Largest US bank by assets with leading investment banking, consumer banking, and asset management.' },
  { ticker: 'V',     name: 'Visa Inc.',                    sector: 'Financials',             description: 'Global payments network with a capital-light model, processing trillions in transactions annually.' },
  { ticker: 'MA',    name: 'Mastercard Incorporated',      sector: 'Financials',             description: 'Second-largest global payments network with high-margin transaction processing and data services.' },
  { ticker: 'BAC',   name: 'Bank of America Corp.',        sector: 'Financials',             description: 'Major US bank serving consumer, small business, and institutional clients with broad digital adoption.' },
  { ticker: 'WFC',   name: 'Wells Fargo & Company',        sector: 'Financials',             description: 'US retail and commercial bank emerging from years of regulatory scrutiny with asset cap in place.' },
  { ticker: 'GS',    name: 'Goldman Sachs Group Inc.',     sector: 'Financials',             description: 'Elite investment bank and asset manager with Global Banking & Markets and Asset & Wealth divisions.' },
  { ticker: 'MS',    name: 'Morgan Stanley',               sector: 'Financials',             description: 'Investment bank and wealth manager with a large fee-based asset management business.' },
  { ticker: 'AXP',   name: 'American Express Company',     sector: 'Financials',             description: 'Premium credit card network and issuer with high-spending card members and closed-loop model.' },
  { ticker: 'BLK',   name: 'BlackRock Inc.',               sector: 'Financials',             description: 'World\'s largest asset manager with $10T+ AUM, iShares ETF franchise, and Aladdin risk platform.' },
  { ticker: 'SPGI',  name: 'S&P Global Inc.',              sector: 'Financials',             description: 'Financial intelligence with S&P ratings, market data, commodity insights, and mobility analytics.' },
  { ticker: 'C',     name: 'Citigroup Inc.',               sector: 'Financials',             description: 'Global bank undergoing a simplification strategy with strength in institutional and treasury services.' },
  { ticker: 'COF',   name: 'Capital One Financial',        sector: 'Financials',             description: 'Credit card and consumer banking company with data-driven underwriting and a large subprime book.' },
  { ticker: 'AIG',   name: 'American International Group', sector: 'Financials',             description: 'Global insurance company offering property, casualty, and life products after post-crisis restructuring.' },
  { ticker: 'PGR',   name: 'The Progressive Corporation',  sector: 'Financials',             description: 'Largest US personal auto insurer with superior data-driven pricing and fast growth in home insurance.' },
  { ticker: 'CB',    name: 'Chubb Limited',                sector: 'Financials',             description: 'World\'s largest publicly traded property and casualty insurer with global commercial and personal lines.' },

  // ── Industrials ──────────────────────────────────────────────────────────
  { ticker: 'RTX',   name: 'RTX Corporation',              sector: 'Industrials',            description: 'Aerospace and defence company with Pratt & Whitney engines and Raytheon missile systems.' },
  { ticker: 'UNP',   name: 'Union Pacific Corporation',    sector: 'Industrials',            description: 'Major US railroad operating 32,000 miles of track connecting the western US.' },
  { ticker: 'HON',   name: 'Honeywell International',      sector: 'Industrials',            description: 'Diversified industrial conglomerate in aerospace, building technologies, and performance materials.' },
  { ticker: 'UPS',   name: 'United Parcel Service Inc.',   sector: 'Industrials',            description: 'Global package delivery and supply chain management company serving e-commerce and B2B.' },
  { ticker: 'BA',    name: 'Boeing Company',               sector: 'Industrials',            description: 'Commercial jet manufacturer and defence contractor navigating major quality and production challenges.' },
  { ticker: 'CAT',   name: 'Caterpillar Inc.',             sector: 'Industrials',            description: 'World\'s largest construction and mining equipment manufacturer with strong services revenue.' },
  { ticker: 'DE',    name: 'Deere & Company',              sector: 'Industrials',            description: 'Leading agricultural and construction equipment maker with precision-ag technology differentiation.' },
  { ticker: 'GE',    name: 'GE Aerospace',                 sector: 'Industrials',            description: 'Jet engine manufacturer (LEAP, GEnx) for commercial and military aircraft post-GE breakup.' },
  { ticker: 'LMT',   name: 'Lockheed Martin Corporation',  sector: 'Industrials',            description: 'Largest US defence contractor with F-35 fighter jet, hypersonics, and space systems.' },
  { ticker: 'NOC',   name: 'Northrop Grumman Corporation', sector: 'Industrials',            description: 'Defence and aerospace systems company with B-21 bomber, space, and cybersecurity businesses.' },
  { ticker: 'FDX',   name: 'FedEx Corporation',            sector: 'Industrials',            description: 'Global express delivery network undergoing a cost restructuring to improve margins.' },
  { ticker: 'WM',    name: 'Waste Management Inc.',        sector: 'Industrials',            description: 'North America\'s largest waste collection, disposal, and recycling company.' },
  { ticker: 'ITW',   name: 'Illinois Tool Works Inc.',     sector: 'Industrials',            description: 'Diversified manufacturer of equipment and consumables with an 80/20 business simplification model.' },

  // ── Energy ────────────────────────────────────────────────────────────────
  { ticker: 'XOM',   name: 'ExxonMobil Corporation',       sector: 'Energy',                 description: 'Largest US oil major with upstream, downstream, and chemical businesses plus Pioneer acquisition.' },
  { ticker: 'CVX',   name: 'Chevron Corporation',          sector: 'Energy',                 description: 'Integrated oil and gas company with strong free cash flow and Hess acquisition pending.' },
  { ticker: 'COP',   name: 'ConocoPhillips',               sector: 'Energy',                 description: 'Pure-play E&P company with low-cost assets across the Permian, Eagle Ford, and Alaska.' },
  { ticker: 'SLB',   name: 'SLB (Schlumberger)',           sector: 'Energy',                 description: 'World\'s largest oilfield services company with drilling technology and digital energy solutions.' },
  { ticker: 'EOG',   name: 'EOG Resources Inc.',           sector: 'Energy',                 description: 'Premier US shale oil company with low breakeven costs in the Permian and Delaware basins.' },
  { ticker: 'VLO',   name: 'Valero Energy Corporation',    sector: 'Energy',                 description: 'Largest US independent petroleum refiner with 15 refineries and renewable diesel capacity.' },
  { ticker: 'MPC',   name: 'Marathon Petroleum Corporation',sector: 'Energy',                description: 'US refining giant operating through MPLX pipeline MLP and 16 refineries.' },

  // ── Materials ─────────────────────────────────────────────────────────────
  { ticker: 'LIN',   name: 'Linde plc',                    sector: 'Materials',              description: 'World\'s largest industrial gas company supplying gases for healthcare, chemicals, and electronics.' },
  { ticker: 'APD',   name: 'Air Products & Chemicals',     sector: 'Materials',              description: 'Industrial gases and hydrogen energy company investing heavily in clean hydrogen infrastructure.' },
  { ticker: 'ECL',   name: 'Ecolab Inc.',                  sector: 'Materials',              description: 'Water treatment, hygiene, and infection prevention solutions for food, healthcare, and hospitality.' },
  { ticker: 'NEM',   name: 'Newmont Corporation',          sector: 'Materials',              description: 'World\'s largest gold mining company with operations across the Americas, Africa, and Australia.' },
  { ticker: 'FCX',   name: 'Freeport-McMoRan Inc.',        sector: 'Materials',              description: 'Leading copper miner with operations in the Americas and Indonesia, benefiting from energy transition.' },

  // ── Utilities ─────────────────────────────────────────────────────────────
  { ticker: 'NEE',   name: 'NextEra Energy Inc.',          sector: 'Utilities',              description: 'Largest US electric utility and world\'s largest renewable energy producer (wind and solar).' },
  { ticker: 'SO',    name: 'Southern Company',             sector: 'Utilities',              description: 'US electric and gas utility serving the Southeast with nuclear, gas, and renewable generation.' },
  { ticker: 'DUK',   name: 'Duke Energy Corporation',      sector: 'Utilities',              description: 'Major US electric utility serving 8M customers across the Carolinas, Midwest, and Florida.' },
  { ticker: 'AEP',   name: 'American Electric Power',      sector: 'Utilities',              description: 'Regulated electric utility with one of the largest transmission networks in the US.' },

  // ── Real Estate ───────────────────────────────────────────────────────────
  { ticker: 'AMT',   name: 'American Tower Corporation',   sector: 'Real Estate',            description: 'Global wireless tower REIT with 220,000+ communications sites across 25+ countries.' },
  { ticker: 'PLD',   name: 'Prologis Inc.',                sector: 'Real Estate',            description: 'World\'s largest logistics real estate REIT with warehouses near major population centres.' },
  { ticker: 'EQIX',  name: 'Equinix Inc.',                 sector: 'Real Estate',            description: 'Global data centre REIT interconnecting businesses, clouds, and networks across 70+ metros.' },
  { ticker: 'SPG',   name: 'Simon Property Group Inc.',    sector: 'Real Estate',            description: 'Largest US mall REIT operating premium shopping centres and outlet destinations.' },
  { ticker: 'O',     name: 'Realty Income Corporation',    sector: 'Real Estate',            description: 'Monthly dividend REIT with 13,000+ properties net-leased to retail and industrial tenants.' },
]
